[package]
name = "crux_time"
description = "Time capability for use with crux_core"
version = "0.12.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["crux_core/typegen"]

[dependencies]
chrono = { version = "0.4.40", features = ["serde"], optional = true }
crux_core = { version = "0.14", path = "../crux_core" }
futures = "0.3.31"
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
serde_json = "1.0.140"
